/// Twitch Session Model
///
/// Contains all credentials harvested from the integrity browser session.
/// These values are injected into API requests and video player headers.
library;

import 'package:smart_twitch_flutter/utils/browser_constants.dart';

/// Represents a complete Twitch session with all required credentials
/// for emulating a legitimate browser session.
class TwitchSession {
  /// The Client-ID header extracted from GQL requests.
  /// This is Twitch's "blessed" client ID, NOT our OAuth client ID.
  final String clientId;

  /// The Client-Integrity token - the key to bypassing Twitch's protection.
  /// This is a JWT-like token generated by Twitch's integrity script.
  final String integrityToken;

  /// Authorization header (Bearer token).
  /// May be null for anonymous sessions.
  final String? authorization;

  /// X-Device-Id header - unique device identifier.
  final String deviceId;

  /// The User-Agent used when harvesting this session.
  /// MUST match the User-Agent used in API requests and video player.
  final String userAgent;

  /// Cookies formatted as a single semicolon-delimited string.
  /// Format: "key=value; key2=value2"
  final String cookieString;

  /// Timestamp when this session was created.
  final DateTime createdAt;

  /// Session expiry time (integrity tokens typically expire in ~20 minutes).
  final DateTime? expiresAt;

  const TwitchSession({
    required this.clientId,
    required this.integrityToken,
    this.authorization,
    required this.deviceId,
    required this.userAgent,
    required this.cookieString,
    required this.createdAt,
    this.expiresAt,
  });

  /// Check if this session is still valid.
  bool get isExpired {
    if (expiresAt == null) {
      // Assume 15-minute validity if no explicit expiry
      return DateTime.now().difference(createdAt).inMinutes > 15;
    }
    return DateTime.now().isAfter(expiresAt!);
  }

  /// Check if session should be refreshed proactively.
  /// Returns true if session will expire in less than 2 minutes.
  bool get shouldRefresh {
    if (expiresAt == null) {
      return DateTime.now().difference(createdAt).inMinutes > 13;
    }
    return DateTime.now().isAfter(expiresAt!.subtract(const Duration(minutes: 2)));
  }

  /// Get headers map for Dio/HTTP requests
  Map<String, String> toRequestHeaders() {
    final headers = <String, String>{
      'Client-ID': clientId,
      'Client-Integrity': integrityToken,
      'X-Device-Id': deviceId,
      'User-Agent': userAgent,
    };

    if (authorization != null && authorization!.isNotEmpty) {
      headers['Authorization'] = authorization!;
    }

    return headers;
  }

  /// Get headers map for fvp/MPV player HTTP requests.
  /// Includes cookies in the headers since MPV doesn't support cookie jars.
  Map<String, String> toPlayerHeaders() {
    final headers = toRequestHeaders();
    
    if (cookieString.isNotEmpty) {
      headers['Cookie'] = cookieString;
    }

    return headers;
  }

  /// Format headers as a single newline-delimited string for MPV.
  /// Format: "Header1: value1\nHeader2: value2"
  String toPlayerHeaderString() {
    return toPlayerHeaders()
        .entries
        .map((e) => '${e.key}: ${e.value}')
        .join('\n');
  }

  @override
  String toString() => 'TwitchSession('
      'clientId: ${clientId.substring(0, 8)}..., '
      'hasIntegrity: ${integrityToken.isNotEmpty}, '
      'hasAuth: ${authorization != null}, '
      'deviceId: ${deviceId.substring(0, 8)}..., '
      'cookies: ${cookieString.length} chars, '
      'createdAt: $createdAt'
      ')';

  /// Create a copy with updated fields
  TwitchSession copyWith({
    String? clientId,
    String? integrityToken,
    String? authorization,
    String? deviceId,
    String? userAgent,
    String? cookieString,
    DateTime? createdAt,
    DateTime? expiresAt,
  }) {
    return TwitchSession(
      clientId: clientId ?? this.clientId,
      integrityToken: integrityToken ?? this.integrityToken,
      authorization: authorization ?? this.authorization,
      deviceId: deviceId ?? this.deviceId,
      userAgent: userAgent ?? this.userAgent,
      cookieString: cookieString ?? this.cookieString,
      createdAt: createdAt ?? this.createdAt,
      expiresAt: expiresAt ?? this.expiresAt,
    );
  }
}

/// Builder for constructing TwitchSession from harvested data.
///
/// Used by TwitchIntegrityService to incrementally build a session
/// as headers and cookies are intercepted.
class TwitchSessionBuilder {
  String? _clientId;
  String? _integrityToken;
  String? _authorization;
  String? _deviceId;
  final Map<String, String> _cookies = {};

  /// Set Client-ID from intercepted header
  void setClientId(String value) {
    _clientId = value;
  }

  /// Set Client-Integrity token from intercepted header
  void setIntegrityToken(String value) {
    _integrityToken = value;
  }

  /// Set Authorization header from intercepted header
  void setAuthorization(String value) {
    _authorization = value;
  }

  /// Set X-Device-Id from intercepted header
  void setDeviceId(String value) {
    _deviceId = value;
  }

  /// Add a cookie from CookieManager
  void addCookie(String name, String value) {
    _cookies[name] = value;
  }

  /// Check if all required fields are present
  bool get isComplete {
    return _clientId != null &&
        _clientId!.isNotEmpty &&
        _integrityToken != null &&
        _integrityToken!.isNotEmpty &&
        _deviceId != null &&
        _deviceId!.isNotEmpty;
  }

  /// Check what's missing (for debugging)
  List<String> get missingFields {
    final missing = <String>[];
    if (_clientId == null || _clientId!.isEmpty) missing.add('clientId');
    if (_integrityToken == null || _integrityToken!.isEmpty) {
      missing.add('integrityToken');
    }
    if (_deviceId == null || _deviceId!.isEmpty) missing.add('deviceId');
    return missing;
  }

  /// Build the session if complete, otherwise return null
  TwitchSession? build() {
    if (!isComplete) {
      return null;
    }

    return TwitchSession(
      clientId: _clientId!,
      integrityToken: _integrityToken!,
      authorization: _authorization,
      deviceId: _deviceId!,
      userAgent: kBrowserUserAgent,
      cookieString: TwitchSessionCookies.formatCookieString(_cookies),
      createdAt: DateTime.now(),
      // Integrity tokens typically expire in ~20 minutes
      expiresAt: DateTime.now().add(const Duration(minutes: 18)),
    );
  }

  /// Reset the builder for a fresh harvest
  void reset() {
    _clientId = null;
    _integrityToken = null;
    _authorization = null;
    _deviceId = null;
    _cookies.clear();
  }

  @override
  String toString() => 'TwitchSessionBuilder('
      'hasClientId: ${_clientId != null}, '
      'hasIntegrity: ${_integrityToken != null}, '
      'hasAuth: ${_authorization != null}, '
      'hasDeviceId: ${_deviceId != null}, '
      'cookies: ${_cookies.length}'
      ')';
}
